name: test
on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: pnpm install
      - name: Run ESLint
        run: eslint .
